const double COST_OF_SANDWICH = 4.75;
const double COST_OF_TOPPING = 0.55;
const double DISCOUNT_AMOUNT = 0.10;
double tip = 0;
double finalTotal = 0;
System.Console.WriteLine("How many sandwiches do you want to order?");
double numberOfSandwiches = double.Parse(Console.ReadLine());
System.Console.WriteLine("How many toppings would you like?");
double numberOfToppings = double.Parse(Console.ReadLine());
System.Console.WriteLine("If you would like please add tip");
tip = double.Parse(Console.ReadLine());
finalTotal = ((numberOfSandwiches * COST_OF_SANDWICH) + (numberOfToppings * COST_OF_TOPPING) + tip)*(1 - DISCOUNT_AMOUNT);
System.Console.WriteLine("Your final total is "+"$ "+(Math.Round(finalTotal, 2)));
